---
build_from:
  aarch64: docker.io/actualbudget/actual-server:26.8.0
  amd64: docker.io/actualbudget/actual-server:26.8.0
args:
  BASHIO_VERSION: 0.17.1
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
